# Generated by Django 6.0.3 on 2026-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usu', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo_usu', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('estado_usu', models.CharField(default='activo', max_length=255)),
                ('foto_usu', models.CharField(blank=True, max_length=255, null=True)),
                ('tema_usu', models.CharField(default='light', max_length=10)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerRols',
            fields=[
                ('id_per_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_per_rol', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('estado_per_rol', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'per_rols',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_per', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_per', models.CharField(max_length=255)),
                ('ap_pat_per', models.CharField(blank=True, max_length=255, null=True)),
                ('cel_per', models.CharField(blank=True, max_length=255, null=True)),
                ('carnet_per', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rols',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('estado_rol', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rols',
                'managed': False,
            },
        ),
    ]
